import { greeting } from './greeting';
import {
  sendEmail as gmailSendEmail,
  replyEmail as gmailReplyEmail,
  forwardEmail as gmailForwardEmail,
  listEmails as gmailListEmails,
  readEmail as gmailReadEmail,
  trashEmail as gmailTrashEmail,
  listLabels as gmailListLabels,
  modifyLabels as gmailModifyLabels,
  batchModifyLabels as gmailBatchModifyLabels,
  listThreads as gmailListThreads,
  getThread as gmailGetThread,
  createDraft as gmailCreateDraft,
  listDrafts as gmailListDrafts,
  getDraft as gmailGetDraft,
  updateDraft as gmailUpdateDraft,
  deleteDraft as gmailDeleteDraft,
  sendDraft as gmailSendDraft,
  getProfile as gmailGetProfile
} from './gmail';
import {
  sendEmail as outlookSendEmail,
  replyEmail as outlookReplyEmail,
  forwardEmail as outlookForwardEmail,
  listEmails as outlookListEmails,
  readEmail as outlookReadEmail,
  trashEmail as outlookTrashEmail,
  listFolders as outlookListFolders,
  moveMessage as outlookMoveMessage,
  batchMoveMessages as outlookBatchMoveMessages,
  listThreads as outlookListThreads,
  getThread as outlookGetThread,
  createDraft as outlookCreateDraft,
  listDrafts as outlookListDrafts,
  getDraft as outlookGetDraft,
  updateDraft as outlookUpdateDraft,
  deleteDraft as outlookDeleteDraft,
  sendDraft as outlookSendDraft,
  getProfile as outlookGetProfile
} from './outlook';
import {
  listResources,
  readResource,
  sendResource,
  searchResources
} from './resources';

// types
import { ToolDefinition } from './types';

export const toolRegistry = new Map<string, ToolDefinition>([
  ['greeting', greeting],
  ['list-resources', listResources],
  ['read-resource', readResource],
  ['send-resource', sendResource],
  ['search-resources', searchResources],
  ['gmail-send-email', gmailSendEmail],
  ['gmail-reply-email', gmailReplyEmail],
  ['gmail-forward-email', gmailForwardEmail],
  ['gmail-list-emails', gmailListEmails],
  ['gmail-read-email', gmailReadEmail],
  ['gmail-trash-email', gmailTrashEmail],
  ['gmail-list-labels', gmailListLabels],
  ['gmail-modify-labels', gmailModifyLabels],
  ['gmail-batch-modify-labels', gmailBatchModifyLabels],
  ['gmail-list-threads', gmailListThreads],
  ['gmail-get-thread', gmailGetThread],
  ['gmail-create-draft', gmailCreateDraft],
  ['gmail-list-drafts', gmailListDrafts],
  ['gmail-get-draft', gmailGetDraft],
  ['gmail-update-draft', gmailUpdateDraft],
  ['gmail-delete-draft', gmailDeleteDraft],
  ['gmail-send-draft', gmailSendDraft],
  ['gmail-get-profile', gmailGetProfile],
  ['outlook-send-email', outlookSendEmail],
  ['outlook-reply-email', outlookReplyEmail],
  ['outlook-forward-email', outlookForwardEmail],
  ['outlook-list-emails', outlookListEmails],
  ['outlook-read-email', outlookReadEmail],
  ['outlook-trash-email', outlookTrashEmail],
  ['outlook-list-folders', outlookListFolders],
  ['outlook-move-message', outlookMoveMessage],
  ['outlook-batch-move-messages', outlookBatchMoveMessages],
  ['outlook-list-threads', outlookListThreads],
  ['outlook-get-thread', outlookGetThread],
  ['outlook-create-draft', outlookCreateDraft],
  ['outlook-list-drafts', outlookListDrafts],
  ['outlook-get-draft', outlookGetDraft],
  ['outlook-update-draft', outlookUpdateDraft],
  ['outlook-delete-draft', outlookDeleteDraft],
  ['outlook-send-draft', outlookSendDraft],
  ['outlook-get-profile', outlookGetProfile]
]);
