name = "ganju-mcp"
main = "dist/index.js"
compatibility_date = "2025-11-17"

compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[build]
command = "npm run build"

[env.development]
name = "ganju-mcp-development"
routes = [
  { pattern = "development-mcp.vocesqueabrazan.com", custom_domain = true },
  { pattern = "*.development-mcp.vocesqueabrazan.com/*", zone_name = "vocesqueabrazan.com" }
]
[env.development.observability]
enabled = true
[env.development.observability.logs]
enabled = true
invocation_logs = true
[env.development.observability.traces]
enabled = false
[env.development.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://development-api.vocesqueabrazan.com"
NEXT_PUBLIC_MCP_URL = "https://development-mcp.vocesqueabrazan.com"
NEXT_PUBLIC_WEB_URL = "https://development-app.vocesqueabrazan.com"
NEXT_PUBLIC_DOMAIN = "vocesqueabrazan.com"
[[env.development.hyperdrive]]
binding = "HYPERDRIVE"
id = "bf3f371679734af2af0b11302b3cb971"
[[env.development.r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "ganju-storage-development"
[[env.development.kv_namespaces]]
binding = "JWKS_CACHE"
id = "566eeced11594b61b719b4782bccf10b"
[[env.development.unsafe.bindings]]
name = "HTTP_ENDPOINT_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }
[[env.development.durable_objects.bindings]]
name = "RESOURCE_HANDLER"
class_name = "ResourceHandler"
script_name = "ganju-api-development"
[[env.development.services]]
binding = "API"
service = "ganju-api-development"

[env.production]
name = "ganju-mcp-production"
routes = [
  { pattern = "mcp.ganju.ai", custom_domain = true },
  { pattern = "*.mcp.ganju.ai/*", zone_name = "ganju.ai" }
]
[env.production.observability]
enabled = true
[env.production.observability.logs]
enabled = true
invocation_logs = true
[env.production.observability.traces]
enabled = false
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://api.ganju.ai"
NEXT_PUBLIC_MCP_URL = "https://mcp.ganju.ai"
NEXT_PUBLIC_WEB_URL = "https://app.ganju.ai"
NEXT_PUBLIC_DOMAIN = "ganju.ai"
[[env.production.hyperdrive]]
binding = "HYPERDRIVE"
id = "c552a4fd338d4025b0442e4737a8635b"
[[env.production.r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "ganju-storage-production"
[[env.production.kv_namespaces]]
binding = "JWKS_CACHE"
id = "909add5eb9fe4b0ca094f11f3a5dd348"
[[env.production.unsafe.bindings]]
name = "HTTP_ENDPOINT_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }
[[env.production.durable_objects.bindings]]
name = "RESOURCE_HANDLER"
class_name = "ResourceHandler"
script_name = "ganju-api-production"
[[env.production.services]]
binding = "API"
service = "ganju-api-production"
